# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20171122_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
