# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone_num', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=300)),
                ('packing_type', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_quote.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_from', models.CharField(max_length=300)),
                ('deliver_to', models.CharField(max_length=300)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_quote.Commodity')),
            ],
        ),
    ]
