# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='clear_forward',
            field=models.BooleanField(default=False),
        ),
    ]
