# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_quote', '0002_commodity_clear_forward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='clear_forward',
            new_name='is_clear_forward',
        ),
    ]
